modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="real_life_mod"
version="1.0.0"
displayName="Real Life Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="airid, MCreator"

[[dependencies.real_life_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




